export type Chains =
  | 'Ethereum'
  | 'Sepolia'
  | 'Polygon'
  | 'OP Mainnet'
  | 'Avalanche'
  | 'BNB Smart Chain'
  | 'Arbitrum One'
  | 'Gnosis'
  | 'Arbitrum Nova'
  | 'zkSync Era'
  | 'Moonbeam'
  | 'Avalanche Fuji'
  | 'Polygon Mumbai'
  | 'Binance Smart Chain Testnet'
